"""empty message

Revision ID: df86fd3405dc
Revises: 444fca53acc4
Create Date: 2019-05-19 19:18:58.249715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df86fd3405dc'
down_revision = '444fca53acc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('case', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('client', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('variable', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('webconfig', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webconfig', 'status')
    op.drop_column('variable', 'status')
    op.drop_column('user', 'status')
    op.drop_column('project', 'status')
    op.drop_column('logs', 'client')
    op.drop_column('case', 'status')
    op.drop_column('api', 'status')
    # ### end Alembic commands ###
